
import { categories } from "../../data/categories";

export default function BaiViet2ChiDao() {
  const article = categories["CHỈ ĐẠO ĐIỀU HÀNH"][1];

  return (
    <div>
      <h1 style={{ fontSize: "18px", fontWeight: 600, color: "#1e3a8a", marginBottom: "12px", lineHeight: "1.5", borderLeft: "4px solid #dc2626", paddingLeft: "16px" }}>
        {article.title}
      </h1>

      <p style={{ fontSize: "17px", fontWeight: "600", lineHeight: "1.7", color: "#333", marginBottom: "24px" }}>
        {"Ngày 21/7/2025, Ban Chỉ đạo ƯPT/BCA có Công điện số 08/CĐ-BCĐ gửi Công an các đơn vị, địa phương về việc tập trung ứng phó với bão số 3 và mưa lũ."}
      </p>

      <p style={{ marginBottom: "16px" }}>Công điện gửi: Thủ trưởng các đơn vị: Cục An ninh kinh tế; Cục An ninh mạng và phòng chống tội phạm sử dụng công nghệ cao; Cục Cảnh sát quản lý hành chính về trật tự xã hội; Cục Cảnh sát phòng cháy, chữa cháy và cứu nạn, cứu hộ; Cục Cảnh sát giao thông; Cục Cảnh sát quản lý trại giam, cơ sở giáo dục bắt buộc, trường giáo dưỡng; Trung tâm dữ liệu quốc gia; Bộ Tư lệnh Cảnh sát cơ động; Cục Kế hoạch và tài chính; Cục Quản lý xây dựng và doanh trại; Cục Trang bị và kho vận; Cục Viễn thông và cơ yếu; Cục Công nghệ thông tin; Cục Y tế; Cục Truyền thông Công an nhân dân;</p>
      <p style={{ marginBottom: "16px" }}>Ban Chỉ huy ƯPT Công an các tỉnh, thành phố: Quảng Ninh, Hải Phòng, Hưng Yên, Ninh Bình, Thanh Hóa, Nghệ An, Hà Tĩnh, Lào Cai, Lai Châu, Điện Biên, Sơn La, Tuyên Quang, Cao Bằng, Lạng Sơn, Thái Nguyên, Phú Thọ, Bắc Ninh, Hà Nội.</p>
      <p style={{ marginBottom: "16px" }}>1. Tiếp tục triển khai thực hiện quyết liệt, nghiêm túc, có hiệu quả các Công điện chỉ đạo của Thủ tướng Chính phủ, Bộ Công an về triển khai ứng phó khẩn cấp với bão số 3 và mưa lũ sau bão, trọng tâm là: Công điện số 117/CĐ-TTg của Thủ tướng Chính phủ; Công điện số 07/CĐ-BCA-V01 ngày 18/7/2025 của Bộ Công an về chủ động ứng phó với diễn biến của bão Wipha. Công an các đơn vị, địa phương ưu tiên tập trung triển khai các nhiệm vụ phòng, chống bão số 3 đến tận cơ sở (thôn, xóm, bản, làng); không tổ chức các cuộc họp nếu không thật sự cần thiết.</p>
      <p style={{ marginBottom: "16px" }}></p>
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenThiLan/thang5/3%20(3).jpeg?width=1000" />
      <p style={{ marginBottom: "16px" }}>2. Yêu cầu Ban chỉ huy ƯPT Công an các đơn vị, địa phương: (1) Chủ động lực lượng thường trực, ứng trực, dự bị sẵn sàng ứng phó với diễn biến của bão trong mọi tình huống; (2) Bảo đảm công tác an ninh trật tự tại cơ sở với mục tiêu bảo đảm an toàn, sức khỏe, tính mạng cho Nhân dân là trên hết, trước hết; (3) Chủ động nắm chắc diễn biến tình hình của bão, mưa lũ, khẩn trương phối hợp rà soát, thống kê chi tiết các khu vực nguy hiểm, có nguy cơ xảy ra mưa lớn, lũ quét, sạt lở đất, khu vực ven biển, cửa sông, ven bờ để kịp thời tham mưu sơ tán, di dời người dân cùng phương tiện, tài sản đến nơi an toàn, kiên quyết không để người dân ở lại trên lồng bè, chòi canh nuôi trồng thủy sản trước và trong khi bão đổ bộ (cần thiết phải cưỡng chế di dời ngay để bảo đảm an toàn); (4) Phối hợp kiểm tra, hướng dẫn neo đậu tầu thuyền tại các khu neo đậu, tránh trú đảm bảo an toàn cháy nổ, an ninh trật tự, xã hội; (5) Chủ động phối hợp chặt chẽ với Bộ đội Biên phòng tổ chức hướng dẫn các chủ phương tiện hoạt động trên biển và người dân biết để ứng phó, không di chuyển vào khu vực nguy hiểm, về nơi tránh trú an toàn và cứu hộ, cứu nạn khi có tình huống xảy ra; (6) Bố trí lực lượng hướng dẫn, phân luồng, cắm biển cảnh báo, bảo đảm an toàn giao thông, kiểm soát chặt chẽ người và phương tiện qua các ngầm, tràn, khu vực ngập sâu, nước chảy xiết, khu vực sạt lở hoặc có nguy cơ xảy ra sạt lở, kiên quyết không để người và phương tiện tham gia giao thông lưu thông khi không bảo đảm an toàn, kiểm soát chặt chẽ việc đi lại, tham gia giao thông của người dân khi bão đổ bộ, hạn chế đến mức thấp nhất thiệt hại về người và tài sản; (7) Tham mưu đề xuất cấm đường vượt biển, cầu vượt biển, phà giao thông, các bến đò ngang trong thời gian bão ảnh hưởng; (8) Tăng cường công tác tuyên truyền, phổ biến, hướng dẫn các biện pháp, kỹ năng ứng phó với thiên tai, sơ cứu ban đầu nhằm giảm thiểu đến mức thấp nhất thiệt hại có thể xảy ra; (9) Phối hợp đảm bảo an toàn hồ đập, thủy điện, công trình có dự án trọng điểm, quan trọng liên quan an ninh quốc gia.</p>
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenPhuongAnh/2025/7/fd5053d6-d435-4ec3-b813-2dc0f8b46b4f.jpg?width=1000" />
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenPhuongAnh/2025/7/e244163c-9501-49d3-b395-efbf00ab4d99.jpg?width=1000" />
      <p style={{ marginBottom: "16px" }}>3. Các đơn vị căn cứ chức năng, nhiệm vụ triển khai thực hiện theo chỉ đạo của Bộ đã được phân công tại Công điện số 07 và Điện số 140, 142 của Văn phòng. Giao các đơn vị Bộ Tư lệnh Cảnh sát cơ động; Cục An ninh mạng và phòng, chống tội phạm sử dụng công nghệ cao; Cục Cảnh sát phòng cháy, chữa cháy và cứu nạn, cứu hộ; Cục Cảnh sát giao thông; Cục Cảnh sát quản lý trại giam, cơ sở giáo dục bắt buộc, trường giáo dưỡng; Cục Kế hoạch và tài chính; Cục Quản lý xây dựng và doanh trại; Cục Trang bị và kho vận; Cục Viễn thông và cơ yếu; Cục Công nghệ thông tin; Cục Y tế sẵn sàng lực lượng, phương tiện, vật tư, cơ số thuốc men, y tế, kinh phí để kịp thời chi viện cho các địa phương trong trường hợp cần thiết; có phương án bảo đảm thông tin liên lạc phục vụ công tác chỉ huy, điều hành trong ứng phó với bão, tổ chức tìm kiếm cứu nạn, cứu hộ, triển khai các phương án đảm bảo vệ sinh môi trường, dịch tễ, phòng, chống dịch bệnh, tai nạn thương tích trong và sau bão. Giao Cục Cảnh sát phòng cháy, chữa cháy và cứu nạn, cứu hộ; Cục Cảnh sát giao thông; Bộ Tư lệnh Cảnh sát cơ động chủ động phương án huy động tăng cường, điều động lực lượng, phương tiện chi viện cho Công an các địa phương bị ảnh hưởng của bão, mưa lũ trong trường hợp cần thiết; Cục Trang bị và kho vận phối hợp chặt chẽ với Công an các đơn vị, địa phương chủ động cấp phát, vận chuyển ngay trang thiết bị, phương tiện phục vụ công tác ứng phó, cứu nạn, cứu hộ và khắc phục hậu quả bão, lũ khi có yêu cầu.</p>
      <p style={{ marginBottom: "16px" }}>4. Tổ chức nghiêm công tác thường trực, ứng trực, dự bị sẵn sàng triển khai các nhiệm vụ bảo đảm an ninh, trật tự và phòng, chống thiên tai; thực hiện nghiêm chế độ trực ban, kịp thời thông tin, báo cáo về Ban Chỉ đạo theo quy định (qua Văn phòng Bộ, SĐT: 069.2299150, 0782401006 hoặc 0979087633)./.</p>
    </div>
  );
}
