import { categories } from "../../data/categories";
import { useEffect } from "react";
export default function BaiViet2BoCongAn() {
  const article = categories["HOẠT ĐỘNG CỦA BỘ CÔNG AN"][1];
  useEffect(() => {
    console.log("bai viet cong an 2");}, []);
  console.log("Article data:", article);
  return (
    <div>
      
      <h1 style={{ fontSize: "18px", fontWeight: 600, color: "#1e3a8a", marginBottom: "12px", lineHeight: "1.5", borderLeft: "4px solid #dc2626", paddingLeft: "16px" }}>
        {article.title}
      </h1>

      <p style={{ fontSize: "17px", fontWeight: "600", lineHeight: "1.7", color: "#333", marginBottom: "24px" }}>
        {"Ngày 23/7/2025, tại Trại giam Phú Sơn 4 (tỉnh Thái Nguyên), Đoàn công tác của Bộ Công an do Thượng tướng Lê Văn Tuyến, Thứ trưởng, Uỷ viên Thường trực Hội đồng tư vấn đặc xá, Trưởng Ban Chỉ đạo về đặc xá của Bộ Công an làm Trưởng đoàn có buổi kiểm tra công tác đặc xá năm 2025 (đợt 2) và các mặt công tác khác tại tỉnh Thái Nguyên và Phú Thọ."}
      </p>

      <p style={{ marginBottom: "16px" }}>Dự Đại hội có các đồng chí: Bùi Thị Minh Hoài, Ủy viên Bộ Chính trị, Bí thư Thành ủy Hà Nội; Trần Sỹ Thanh, Uỷ viên Trung ương Đảng, Phó Bí thư Thành uỷ, Chủ tịch Ủy ban nhân dân thành phố Hà Nội. Cùng dự có lãnh đạo các cục nghiệp vụ thuộc Bộ Công an; lãnh đạo các ban đảng, sở, ngành, đoàn thể thành phố; Bí thư Đảng uỷ các xã, phường thuộc thành phố Hà Nội; các đồng chí nguyên lãnh đạo Công an thành phố qua các thời kỳ…"</p>
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenThiLan/thang5/z6833405188514_5f0b64350164f78504c210708a929c9a.jpg?width=1000" />
      <p style={{ marginBottom: "16px" }}>Báo cáo tại Đại hội nêu rõ, Đảng bộ Công an thành phố Hà Nội nhiệm kỳ 2025 - 2030 đã khẳng định rõ nét năng lực lãnh đạo, sức chiến đấu trong lãnh đạo, chỉ đạo các mặt công tác bảo đảm an ninh, trật tự và xây dựng lực lượng Công an Thủ đô. Các nghị quyết, chỉ thị, kết luận của Đảng đều được Đảng bộ Công an thành phố thể chế hóa, cụ thể hóa và lãnh đạo thực hiện có hiệu quả. Qua đó, xây dựng Đảng bộ Công an thành phố đoàn kết, thống nhất về ý chí, hành động; cán bộ, chiến sĩ tận tâm, tận lực, tận tuỵ, không quản khó khăn, gian khổ, bảo đảm an ninh, trật tự, phòng chống tội phạm, tiên phong trong chuyển đổi số; thực hiện thắng lợi Nghị quyết Đại hội Công an thành phố lần thứ XXVIII.</p>
      <p>Trong lãnh đạo thực hiện nhiệm vụ chính trị, Đảng bộ Công an thành phố Hà Nội đã bám sát quan điểm, chủ trương của Đảng, Đảng uỷ Công an Trung ương, Thành uỷ, tập trung chỉ đạo triển khai có hiệu quả nhiều giải pháp giữ vững an ninh, trật tự, đóng góp tích cực vào phát triển kinh tế - xã hội của Thủ đô. Trong bối cảnh tình hình an ninh, trật tự trên địa bàn rất phức tạp, Công an thành phố Hà Nội đã giữ vững an ninh quốc gia, bảo vệ tuyệt đối an ninh, an toàn các sự kiện chính trị quan trọng dày đặc trên địa bàn, không để xảy ra bị động, bất ngờ. Tích cực đấu tranh trấn áp tội phạm, kéo giảm tội phạm bền vững, xây dựng xã hội trật tự kỷ cương, an toàn, lành mạnh. Huy động sức mạnh tổng hợp của cả hệ thống chính trị tham gia bảo vệ an ninh, trật tự được triển khai sáng tạo, hiệu quả, đạt nhiều kết quả tích cực.</p>
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenThiLan/thang5/z6833405172461_a46593d2b0b44777b3da55934849142d.jpg?width=1000" />
      <p style={{ marginBottom: "16px" }}>Trong lãnh đạo công tác xây dựng Đảng, xây dựng lực lượng, Đảng bộ Công an thành phố Hà Nội đã đổi mới phương thức lãnh đạo; đảm bảo nguyên tắc tập trung dân chủ; có nhiều đổi mới về tư duy, phong cách làm việc; tập trung lãnh đạo thực hiện có hiệu quả các nhiệm vụ chiến lược, cấp bách, kịp thời tháo gỡ khó khăn, vướng mắc, nâng cao chất lượng các mặt công tác, dẫn dắt lực lượng Công an thành phố thật sự trở thành điểm tựa bình yên của Nhân dân Thủ đô. Tham mưu, tổ chức thực hiện hiệu quả Nghị quyết số 12 của Bộ Chính trị về xây dựng lực lượng Công an nhân dân thật sự trong sạch, vững mạnh, chính quy, tinh nhuệ, hiện đại. Quyết liệt lãnh đạo sắp xếp, kiện toàn tổ chức bộ máy theo đúng hướng dẫn của Trung ương, Đảng uỷ Công an Trung ương…</p>
      <p style={{ marginBottom: "16px" }}>Tại Đại hội, các đại biểu đã tiến hành bầu Ban Chấp hành Đảng bộ Công an thành phố lần thứ XXIX, nhiệm kỳ 2025 – 2030 gồm 27 đồng chí; bầu Đoàn đại biểu dự Đại hội Đảng bộ thành phố Hà Nội lần thứ XVIII gồm 09 đồng chí; biểu quyết thông qua Nghị quyết Đại hội…</p>
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenThiLan/thang5/6ab257f2d4935dcd0482.jpg?width=1000" />
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenThiLan/thang5/fd8421eba28a2bd4729b.jpg?width=1000" />
      <p style={{ marginBottom: "16px" }}>Phát biểu tại Đại hội, Chủ tịch Ủy ban nhân dân thành phố Hà Nội- Trần Sỹ Thanh khẳng định, trong nhiệm kỳ qua, Đảng bộ Công an thành phố Hà Nội đã thực hiện rất tốt vai trò nòng cốt trong công tác bảo vệ an ninh chính trị, bảo đảm trật tự, an toàn xã hội trên địa bàn Thủ đô. Chủ động nắm chắc tình hình, tham mưu kịp thời với Thành ủy, Ủy ban nhân dân thành phố lãnh đạo, chỉ đạo triển khai các giải pháp giữ vững ổn định an ninh chính trị, trật tự, an toàn xã hội trong mọi tình huống.</p>
      <p style={{ marginBottom: "16px" }}>Đồng chí Chủ tịch Ủy ban nhân dân thành phố bày tỏ sự trân trọng, đánh giá cao công tác phối hợp lãnh đạo, chỉ đạo chặt chẽ, thường xuyên, sâu sát, toàn diện, hiệu quả của Đảng ủy Công an Trung ương, lãnh đạo Bộ Công an đối với Đảng bộ, Ban Giám đốc và toàn lực lượng Công an thành phố Hà Nội trong suốt thời gian qua; mong muốn mối quan hệ phối hợp giữa Đảng ủy Công an Trung ương, lãnh đạo Bộ Công an và Thành ủy, Hội đồng nhân dân, Ủy ban nhân dân thành phố sẽ tiếp tục được củng cố, tăng cường, nâng tầm hơn nữa về chiều sâu, hiệu quả.</p>
      <img style={{ width: "100%", maxWidth: "768px", display: "block", margin: "0 auto 24px auto", borderRadius: "8px", boxShadow: "0 2px 6px rgba(0,0,0,0.15)" }} src="https://bocongan.gov.vn/knd/tt/PublishingImages/NguyenThiLan/thang5/084a6695.jpg?width=1000" />
      <p style={{ marginBottom: "16px" }}>Đồng chí tin tưởng, bằng quyết tâm chính trị cao nhất, tinh thần đoàn kết, dân chủ, kỷ cương, đột phá, phát triển, Đại hội lần thứ XXIX của Đảng bộ Công an thành phố sẽ là mốc son quan trọng để toàn lực lượng Công an Thủ đô thực hiện thắng lợi các mục tiêu, nhiệm vụ Nghị quyết Đại hội đề ra, tiếp tục vững bước trên chặng đường mới, xứng đáng là chỗ dựa vững chắc của Đảng bộ, chính quyền và Nhân dân Thủ đô Hà Nội.</p>
      <p style={{ marginBottom: "16px" }}>Chỉ đạo một số nhiệm vụ trong nhiệm kỳ 2025 – 2030, Bộ trưởng Lương Tam Quang nhấn mạnh, Đảng bộ Công an thành phố phải tiếp tục khẳng định vai trò đi đầu trong toàn lực lượng Công an nhân dân triển khai tư duy mới về bảo vệ an ninh, trật tự trong giai đoạn cách mạng mới. An ninh, trật tự phải đóng vai trò nền tảng cho thành công của phát triển; lực lượng Công an nhân dân cùng với thực hiện nhiệm vụ bảo vệ an ninh, trật tự, phải tích cực đồng hành, hỗ trợ hệ thống chính trị, toàn dân thực hiện có hiệu quả các chủ trương của Đảng, chính sách pháp luật của Nhà nước, công tác công an phải tạo thuận lợi cao nhất cho phát triển.</p>
      <p style={{ marginBottom: "16px" }}>Đảng bộ Công an thành phố tập trung lãnh đạo vận hành hiệu năng, hiệu lực, hiệu quả mô hình Công an hai cấp theo đúng tinh thần đồng chí Tổng Bí thư đã nhấn mạnh “Hàng thẳng, lối thông, đồng lòng cùng tiến”. Lãnh đạo thực hiện tốt nhiệm vụ chính trị với tinh thần Công an Hà Nội phải làm gương, là kiểu mẫu của cả nước, đóng góp tích cực cho phát triển của Thủ đô. Tiếp tục kéo giảm bền vững tội phạm, không để tội phạm lộng hành, gây bức xúc trong Nhân dân; tập trung xây dựng các xã không ma tuý, không tội phạm.</p>
      <p style={{ marginBottom: "16px" }}>Bộ trưởng Lương Tam Quang yêu cầu, Đảng bộ Công an thành phố siết chặt quản lý nhà nước về an ninh, trật tự; đi đầu trong phòng, chống ô nhiễm môi trường; có giải pháp tạo chuyển biến mạnh mẽ việc thi hành pháp luật của Nhân dân, góp phần xây dựng Thủ đô xanh, sạch, hiện đại, kỷ cương, an toàn, đáng sống. Thúc đẩy mạnh mẽ chuyển đổi số, tham gia tích cực xây dựng các cơ sở dữ liệu, phát triển công nghiệp an ninh. Đi đầu thực hiện và tham mưu, đồng hành, hỗ trợ hệ thống chính trị, toàn dân thực hiện thắng lợi các chủ trương chiến lược của Đảng, trọng tâm là “Bộ tứ trụ cột” 04 Nghị quyết của Bộ Chính trị.</p>
    </div>
  );
}

