import { categories } from "../../data/categories";

export default function BaiViet1ChiDao() {
  const article = categories["CHỈ ĐẠO ĐIỀU HÀNH"][0];

  return (
    <div>
      <h1 style={{ fontSize: "18px", fontWeight: 600, color: "#1e3a8a", marginBottom: "12px", lineHeight: "1.5", borderLeft: "4px solid #dc2626", paddingLeft: "16px" }}>
        {article.title}
      </h1>

      <p style={{ fontSize: "17px", fontWeight: "600", lineHeight: "1.7", color: "#333", marginBottom: "24px" }}>
        {"Ngày 23/7/2025, Ban Chỉ đạo ƯPT/BCA có Công điện số 09/CĐ-BCĐ gửi Công an các đơn vị, địa phương về việc chủ động ứng phó với mưa lớn, lũ, ngập lụt, lũ quét, sạt lở đất"}
      </p>

      <p style={{ marginBottom: "16px" }}>Công điện gửi: Thủ trưởng các đơn vị: Cục An ninh kinh tế; Cục Cảnh sát phòng chống tội phạm về môi trường; Cục Cảnh sát quản lý hành chính về trật tự xã hội; Cục Cảnh sát phòng cháy, chữa cháy và cứu nạn, cứu hộ; Cục Cảnh sát giao thông; Cục Cảnh sát quản lý trại giam, cơ sở giáo dục bắt buộc, trường giáo dưỡng; Bộ Tư lệnh Cảnh sát cơ động; Cục Kế hoạch và tài chính; Cục Quản lý xây dựng và doanh trại; Cục Trang bị và kho vận; Cục Viễn thông và cơ yếu; Cục Công nghệ thông tin; Cục Y tế; Cục Truyền thông Công an nhân dân;</p>
      <p style={{ marginBottom: "16px" }}>Ban Chỉ huy ƯPT Công an các tỉnh, thành phố: Hà Nội, Hải Phòng, Tuyên Quang, Lào Cai, Lai Châu, Điện Biên, Lạng Sơn, Cao Bằng, Sơn La, Thái Nguyên, Phú Thọ, Quảng Ninh, Bắc Ninh, Hưng Yên, Ninh Bình, Thanh Hóa, Nghệ An, Hà Tĩnh.</p>
      <p style={{ marginBottom: "16px" }}>Từ ngày 24/7 đến ngày 25/7, ở khu vực Bắc Bộ, Thanh Hóa và Nghệ An có khả năng xảy ra một đợt mưa lớn diện rộng với lượng mưa phổ biến 60-120mm, cục bộ có nơi trên 200mm, cảnh báo nguy cơ mưa có cường suất lớn (90mm/3h). Thực hiện nghiêm Công điện số 119/CĐ-TTg ngày 22/7/2025 của Thủ tướng Chính phủ về việc tập trung ứng phó khẩn cấp với mưa lũ trên lưu vực sông Cả; để chủ động ứng phó với mưa lớn, lũ, ngập lụt, lũ quét, sạt lở đất, bảo đảm an toàn tính mạng và tài sản của Nhân dân, an toàn công trình đê điều, hồ đập thủy lợi, Ban chỉ đạo ƯPT/BCA yêu cầu Ban chỉ huy ƯPT Công an các đơn vị, địa phương chỉ đạo, triển khai thực hiện ngay một số nhiệm vụ sau</p>
      <p style={{ marginBottom: "16px" }}>1. Tập trung: (1) Thực hiện quyết liệt, nghiêm túc, có hiệu quả các Công điện chỉ đạo của Thủ tướng Chính phủ, Bộ Công an về triển khai ứng phó khẩn cấp với bão số 3 và mưa, lũ sau bão; (2) Bám sát, kỹ, chủ động nắm chắc tình hình về diễn biến của mưa lớn; (3) Chủ động tất cả kế hoạch, phương án bảo đảm tốt công tác an ninh, trật tự tại cơ sở để kịp thời ứng phó, không để bị động, bất ngờ; (4) Cần tổ chức dày dặn, phong phú công tác thông tin, tuyên truyền, hướng dẫn người dân về tình hình, diễn biến, kỹ năng ứng phó với các tình huống sự cố, thiên tai, cứu nạn, cứu hộ nhằm giảm thiểu đến mức thấp nhất thiệt hại có thể xảy ra; phản ánh chân thực hình ảnh, hoạt động công tác bảo đảm an ninh trật tự, tìm kiếm cứu nạn, cứu hộ, phòng, chống, khắc phục hậu quả thiên tai của lực lượng Công an nhân dân; (5) Bảo đảm an toàn về tính mạng, sức khỏe cho các lực lượng trực tiếp làm nhiệm vụ và an toàn về các lực lượng, trụ sở, cơ sở giam giữ, tài liệu, trang thiết bị làm việc của lực lượng Công an nhân dân.</p>
      <p style={{ marginBottom: "16px" }}>2. Lập sơ đồ tác chiến, ứng phó các khu vực trọng điểm, xung yếu có nguy cơ xảy ra sự cố công trình, lũ ống, lũ quét, sạt lở đất, ngập lụt sâu tổ chức bố trí lực lượng, phương tiện, vật tư trang thiết bị sẵn sàng hỗ trợ địa phương và Nhân dân ứng phó mưa lũ, cứu nạn, cứu hộ khi có yêu cầu; hướng dẫn, phân luồng, cắm biển cảnh báo, phối hợp khắc phục sự cố, bảo đảm giao thông thông suốt trên các trục giao thông chính, cấm cứng người và phương tiện qua lại nếu không bảo đảm an toàn; phối hợp triển khai các biện pháp đảm bảo an toàn đê điều, hồ đập thủy lợi, thủy điện, công trình có dự án trọng điểm, quan trọng liên quan an ninh quốc gia, an toàn của người dân khi xả lũ đối với vùng hạ lưu.</p>
      <p style={{ marginBottom: "16px" }}>3. Ban chỉ huy ƯPT Công an tỉnh Nghệ An: (1)Triển khai ngay lực lượng, phương tiện phối hợp thực hiện nhiệm vụ tìm kiếm cứu nạn, cứu hộ, ứng phó, khắc phục hậu quả mưa lũ kéo dài, phòng chống hộ đê, xử lý các sự cố “ngay từ giờ đầu”, không để bị động, bất ngờ, nhất là đập thủy điện Bản Vẽ; (2)Tham mưu cấp ủy, chính quyền địa phương chỉ đạo phương án bảo vệ các trọng điểm đê điều xung yếu theo phương châm “4 tại chỗ” (chỉ huy tại chỗ; lực lượng tại chỗ; phương tiện, vật tư tại chỗ; hậu cần tại chỗ), rà soát, kiểm tra các khu vực nguy hiểm, mất an toàn để có phương án sơ tán, di dời, bảo đảm an ninh trật tự, an toàn tính mạng cho người dân, kiên quyết không để người dân ở lại các khu vực nguy hiểm khi lũ lên cao (trường hợp cần thiết phải chủ động cưỡng chế di dời để bảo đảm an toàn tính mạng cho người dân); (3)Bảo đảm an ninh, trật tự, an toàn tính mạng, tài sản cho người dân và Nhà nước, phòng chống tội phạm, nhất là tội phạm lợi dụng thiên tai để hoạt động tại các khu vực sơ tán dân cư đi và đến.</p>
      <p style={{ marginBottom: "16px" }}>4. Các đơn vị chức năng của Bộ (K02, C07, C08, C10, H01, H02, H03, H04, H05, H06) sẵn sàng lực lượng, phương tiện, vật tư, cơ số thuốc men, y tế, kinh phí để kịp thời chi viện cho các địa phương trong trường hợp cần thiết; có phương án bảo đảm thông tin liên lạc phục vụ công tác chỉ huy, điều hành trong ứng phó với thiên tai, tổ chức tìm kiếm cứu nạn, cứu hộ, triển khai các phương án đảm bảo vệ sinh môi trường, dịch tễ, phòng, chống dịch bệnh, tai nạn thương tích trong và sau thiên tai.</p>
      <p style={{ marginBottom: "16px" }}>5. Tổ chức nghiêm công tác thường trực, ứng trực, dự bị sẵn sàng triển khai các nhiệm vụ bảo đảm an ninh, trật tự và phòng, chống thiên tai; thực hiện nghiêm chế độ trực ban, kịp thời thông tin, báo cáo về Ban Chỉ đạo theo quy định (qua Văn phòng Bộ, SĐT: 069.2299150, 0782401006 hoặc 0979087633)./.</p>
    </div>
  );
}
